networks:
  cluster-net:
      name: ceph-cluster-net
      external: true
services:
  mon1:
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    hostname: "ceph-mon1-host"
    command: "mon"
    environment:
      MON_IP: ${MON1_IP}
      CEPH_PUBLIC_NETWORK: ${MON1_CEPH_PUBLIC_NETWORK}
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
    networks:
      cluster-net:
        ipv4_address: ${MON1_IP}

  mgr:
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    hostname: "ceph-mgr-host"
    command: "mgr"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
    depends_on:
      - mon1
    networks:
      - cluster-net
    ports:
      - ${DASHBOARD_PORT}:${INTERNAL_DASHBOARD_PORT}

  osd1:
    pid: host
    hostname: "ceph-osd1"
    container_name: "ceph-osd1"
    privileged: true
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    command: "osd_directory_single"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
      - ${OSD_PATH}/osd1:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      cluster-net:
        ipv4_address: ${OSD1_IP}
    # networks:
      # - cluster-net
    restart: always

  osd2:
    pid: host
    hostname: "ceph-osd2"
    container_name: "ceph-osd2"
    privileged: true
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    command: "osd_directory_single"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
      - ${OSD_PATH}/osd2:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      cluster-net:
        ipv4_address: ${OSD2_IP}
    restart: always

  osd3:
    pid: host
    hostname: "ceph-osd3"
    container_name: "ceph-osd3"
    privileged: true
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    command: "osd_directory_single"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
      - ${OSD_PATH}/osd3:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      cluster-net:
        ipv4_address: ${OSD3_IP}
    restart: always
  
  osd4:
    pid: host
    hostname: "ceph-osd4"
    container_name: "ceph-osd4"
    privileged: true
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    command: "osd_directory_single"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
      - ${OSD_PATH}/osd4:/var/lib/ceph/osd
    depends_on:
      - mon1
    networks:
      cluster-net:
        ipv4_address: ${OSD4_IP}
    restart: always
    
  rgw1:
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    hostname: "ceph-rgw1-host"
    command: "rgw"
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
    depends_on:
      - osd1
      - osd2
      - osd3
      - osd4
    networks:
      - cluster-net
    ports:
      - ${RGW_PORT}:7480
    restart: always

  mds1:
    image: quay.io/ceph/daemon:${CEPH_CONTAINER_VERSION}
    command: "mds"
    hostname: "ceph-mds1-host"
    environment:
      CEPHFS_CREATE: 1
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/ceph:/etc/ceph
      - ${VOLUMES_PATH}/lib/:/var/lib/ceph/
    depends_on:
      - osd1
      - osd2
      - osd3
      - osd4
    networks:
      - cluster-net
